### ISSUE TITLE
 matrix in BatesEA_05_GrapNexus.nex was scrambled when printed; original no longer exists

### ISSUE THREAD

**Issue by dwbapst** [rossmounce/cladistic-data#3]
Apologies that it has taken me a few years to add this issue, but I recommend removing/ignoring the matrix for Bates et al. 2005 (or somehow flagging it as bad data) on retiolitid graptolites. The printed cladistic matrix presented in the article (which you appear to have transcribed as printed) wasn't the one used for the presented analysis, and what is printed is a scrambled matrix that has no relationship to the printed character list. The scrambling apparently occurred somewhere in the publishing process.

I first realized this when I noticed that some of the states coded were greater than the number of states listed for that character. I spent some time a few years ago trying to obtain the original matrix, which was last held onto by one of the co-authors (Alf Lenz), but Alf does not have any of the files anymore. So, that matrix is lost in time, and there's no way to recreate the matrix now without re-coding the taxa in the analysis.

**Comment by rossmounce** [comment]
Thanks. I have deleted the matrix content with a link to this issue
